### product get
curl --request GET \
  --url http://localhost:8080/products/1

### product JSON get
curl --request GET \
  --url http://localhost:8080/products/1 \
  --header 'accept: application/json' \
  --header 'authorization: Bearer <>'

### product create
curl --request POST \
  --url http://localhost:8080/products \
  --header 'content-type: application/json' \
  --data '{
  "name": "product 1",
  "price": 1000
}'

### get css
curl --request GET \
  --url http://localhost:8080/css/output.css


### create group
curl --request POST \
  --url http://localhost:8080/groups \
  --header 'content-type: application/json' \
  --header 'accept: application/json' \
  --header 'Authorization: Bearer <>'
  --data '{
    "group_name": "group 1"
  }'