# fly.toml app configuration file generated for squabble-be on 2024-01-22T22:38:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "squabble-be"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_TARGETS = "cmd/planetscaled/"

[env]
  PORT = "8080"
  APP_ENV = "production"
  AUTH0_DOMAIN = "https://squabble.us.auth0.com"
  AUTH0_AUDIENCE = "https://squabble-be.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
